### ISSUE TITLE
Barrel system

### ISSUE THREAD

**Issue by AlphaBeta906** [AlphaBeta906/BloodAlchemy2#3]
## Introduction
The Barrel System is a way to prevent watts from being hoarded by users. Basically a barrel can store 200 watts (can be upgraded,) and will decay. The decay cycle will last 25 days (also can be upgraded,) and it won't automatically self-delete (very intentional game design system ~~not because I can't program it~~.)

## Tasks
- [ ] Generate a basic form of a barrel with watts and date (upgrades will be added later)
- [ ] Show watts that a barrel has
- [ ] Delete/add barrels
- [ ] Use barrels in some sort of shop (future task)

**Comment by AlphaBeta906** [comment]
Too complicated of a solution for watt hoarding
